### ISSUE TITLE
`make future` fails on mac

### ISSUE THREAD

**Issue by felixboehm** [owncloud/nexus#40]
```
# EOS_UTF8=1 enables utf8 filenames
# EOS_NS_ACCOUNTING=1 enables dir size propagation
# EOS_SYNCTIME_ACCOUNTING=1 enables mtime propagation in general
#  - needs the sys.mtime.propagation=1 on a home dir, see below
#  - sys.allow.oc.sync=1 is not needed, it is an option for the oes built in webdav endpoint
sed -i "s/--name eos-mgm-test --net/--name eos-mgm-test --env EOS_UTF8=1 --env EOS_NS_ACCOUNTING=1 --env EOS_SYNCTIME_ACCOUNTING=1 --net/" ./build/eos-docker/src/scripts/start_services.sh
sed: 1: "./build/eos-docker/src/ ...": invalid command code .
make: *** [start-eos] Error 1
```

**Comment by markisatacomputer** [comment]
I edited line 171 so that i option has an empty argument ([link](https://stackoverflow.com/questions/19456518/invalid-command-code-despite-escaping-periods-using-sed)) and that was enough to for make to finish on osx.

`
sed -i '' "s/--name eos-mgm-test --net/--name eos-mgm-test --env EOS_UTF8=1 --env EOS_NS_ACCOUNTING=1 --env EOS_SYNCTIME_ACCOUNTING=1 --net/" ./build/eos-docker/src/scripts/start_services.sh
`

**Comment by tboerger** [comment]
The -i option requires an attribute on Mac. You got to add a switch depending on the platform because it won't work platform independent.

**Comment by butonic** [comment]
fixed in master, see https://github.com/owncloud/nexus/pull/35/files#diff-b67911656ef5d18c4ae36cb6741b7965R242
